name: maibo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  http: ^1.1.0
  url_launcher: ^6.1.12
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.0.9
  convex_bottom_bar: ^3.2.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.jpg"

flutter: 
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

